### ISSUE TITLE
[BUG] [PullRequestUtils]: Support link is 404

### ISSUE THREAD

**Issue by badsyntax** [joachimdalen/AzureDevOpsExtensions#7]
**Describe the bug**

When running the extension in ADO pipelines, the following is displayed:

```console
Starting: Add test report links to pull request
==============================================================================
Task         : Pull Request Comments
Description  : Add comments to a pull request
Version      : 0.2.1
Author       : Joachim Dalen
Help         : [Learn more about this task](https://dev.azure.com/dalenapps/Extensions/PullRequestUtils/README.md
==============================================================================
Finishing: Add test report links to pull request
````

There's 2 issues:

- Invalid markup
- Invalid URL (https://dev.azure.com/dalenapps/Extensions/PullRequestUtils/README.md doesn't exist)

**Agent Type**
- [x] Hosted
- [ ] Self Hosted

**Agent OS**
- [ ] Windows
- [ ] Linux
- [x] OSX

**Comment by joachimdalen** [comment]
Hey! 

Not sure how I haven't noticed this yet, so thanks for reporting it. The link should really just point to marketplace while I work on getting the [documentation site](https://devops-extensions.github.io/docs/#/?id=general) fully up and running, so I'll update that for now. Also in the progress with looking through everything before I open source all of my extensions.

**Comment by joachimdalen** [comment]
I pushed an updated version (0.5.2) that uses the correct links, but the task will still show the format as raw markdown `[Learn more about this task](https://marketplace.visualstudio.com/items?itemName=joachimdalen.pull-request-utils)` since the task uses the `helpMarkDown` field, but does not actually render it as Markdown.

**Comment by badsyntax** [comment]
Thanks! `helpMarkDown` is really misleading 😆 I've noticed all the default tasks don't use markdown here, for example:

```console
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
```

Perhaps just add the link without the link text? The task output will convert plain URL's to HTML anchors.

**Comment by joachimdalen** [comment]
The actual markdown is used other places, like:
![image](https://user-images.githubusercontent.com/15696189/125746068-996cd006-1aca-442c-bf5b-a8ca84949e46.png)

Though, taking a look at the task schema and some of the default tasks (like CmdLineV2), it seems there is an additional option [helpUrl](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CmdLineV2/task.json#L6) that can be set. I'm guessing they might have `helpMarkDown` as a fallback if that isn't set. (Should probably have looked at this before I "fixed" it :sweat: )

![image](https://user-images.githubusercontent.com/15696189/125746380-7a5c45f8-fdf8-4d32-92dd-60fbb0313b24.png)

Since the link is correct now I won't push out a new update. I will update the definition and it will roll out with the next update.

> Note for self: Verify this link for EnvTransform, PullRequestUtils, GitGuard and NpmAuditReport

**Comment by joachimdalen** [comment]
A new version with correct links has been pushed :smile:
