### ISSUE TITLE
[FEATURE]: Provide PullRequestUtils also for Azure DevOps Server

### ISSUE THREAD

**Issue by marc-mueller** [joachimdalen/AzureDevOpsExtensions#8]
**Is your feature request related to a problem? Please describe.**
Is there any reason why the PullRequestUtils extension is only available for Azure DevOps Services? It would be nice to use this extension also on-premises.

**Describe the solution you'd like**
Support for Azure DevOps Services and Azure DevOps Server

**Comment by joachimdalen** [comment]
Hi there!

Limiting support to only Azure DevOps Services was a conscious decision due to some limitations. I don't remember fully right now, but I think it was due to some API endpoints not being available in Server yet.

I will take a look over the code again and see if support for Azure DevOps Server can be enabled.

**Comment by joachimdalen** [comment]
Hi again!

I enabled and pushed a new version with support for Azure DevOps Server enabled. I do not have a server instance to verify on, so please let me know if you face any issues if you use the extension on a server.

**Comment by marc-mueller** [comment]
Thanks a lot for your fast support! I was on vacation till this week. We deployed this extension on an on-premises Azure DevOps instance and so far so good. I'll keep you updated if we encounter any problems.
